import {useEffect,useState} from 'react';
import type {RecordRow} from '../../shared/domain.ts';
import {api} from './api.ts';
import {Button,ErrorBox} from './ui.tsx';
import './audit-graph.css';
export function AuditGraph({company,records,open}:{company:string;records:RecordRow[];open:(r:RecordRow)=>void}){
 const [graph,setGraph]=useState<any>(null),[error,setError]=useState(''),[area,setArea]=useState(''),[team,setTeam]=useState(''),[system,setSystem]=useState('');
 useEffect(()=>{let active=true;api(`/v1/companies/${company}/graph?limit=150`).then(g=>{if(active)setGraph(g)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[company,records]);
 const activeRecords=records.filter(r=>!['retracted','withdrawn'].includes(r.state));
 const people=activeRecords.filter(r=>r.kind==='person');
 const tasks=activeRecords.filter(r=>r.kind==='task'&&r.data.controlAreas?.length);
 const edges=graph?.edges||[];
 const paths=activeRecords.filter(r=>r.kind==='agent').flatMap(agent=>tasks.filter(task=>edges.some((e:any)=>e.source===agent.id&&e.target===task.id&&e.relationship==='BOUND_TO')).map(task=>({agent,task,owner:people.find(p=>edges.some((e:any)=>e.source===p.id&&e.target===agent.id&&e.relationship==='ACCOUNTABLE_FOR'))}))).filter(p=>(!area||p.task.data.controlAreas.includes(area))&&(!team||p.owner?.data.team===team)&&(!system||p.task.data.systems.includes(system)));
 return <section className="audit-graph"><h2>Which agents touch control-related work?</h2><p>Follow the recorded human owner, agent proposal, task, and software. Control areas are review mappings, not an audit opinion or proof of effective controls. Agent records may be drafts.</p>
 <div className="actions">{['Access review','Change review','Confidential data'].map(a=><Button key={a} onClick={()=>{setArea(a);setTeam('');setSystem('')}}>{a}</Button>)}<Button onClick={()=>{setArea('');setTeam('');setSystem('')}}>All mapped agents</Button></div>
 <div className="audit-filters"><label>Control area<select value={area} onChange={e=>setArea(e.target.value)}><option value="">All mapped areas</option>{['Access review','Change review','Confidential data'].map(a=><option key={a}>{a}</option>)}</select></label><label>Owner’s department<select value={team} onChange={e=>setTeam(e.target.value)}><option value="">All departments</option>{[...new Set(people.map(p=>p.data.team))].sort().map(t=><option key={t}>{t}</option>)}</select></label><label>Task software<select value={system} onChange={e=>setSystem(e.target.value)}><option value="">All software</option>{[...new Set(tasks.flatMap(t=>t.data.systems as string[]))].sort().map(s=><option key={s}>{s}</option>)}</select></label></div>
 {error&&<ErrorBox error={error}/>}<p aria-live="polite">{graph?`${new Set(paths.map(p=>p.agent.id)).size} mapped agents · ${paths.length} task paths · ${graph.engine}`:'Loading graph relationships…'}{graph?.truncated||graph?.scanTruncated?' · Partial graph: more records exist beyond this view.':''}</p>
 {graph&&!paths.length&&<p>No matching recorded paths. Change the filters. Unmapped tasks and undiscovered agents are not included.</p>}
 <div className="audit-paths">{paths.map(({agent,task,owner})=><article key={agent.id+task.id}><div className="audit-path"><button onClick={()=>owner&&open(owner)} disabled={!owner}><small>Human owner</small><strong>{owner?.title||'Owner not in this view'}</strong><span>{owner?.data.team}</span></button><span aria-hidden="true">→</span><button onClick={()=>open(agent)}><small>Agent · {agent.state}</small><strong>{agent.title}</strong><span>Proposed for this task</span></button><span aria-hidden="true">→</span><button onClick={()=>open(task)}><small>Task · {task.state}</small><strong>{task.title}</strong><span>{task.data.controlAreas.join(' · ')}</span></button><span aria-hidden="true">→</span><div><small>Software listed on task</small><strong>{task.data.systems.join(', ')}</strong><span>Not a verified connection or access grant</span></div></div><p>{task.data.humanGate}</p><div className="actions">{activeRecords.filter(r=>edges.some((e:any)=>e.source===task.id&&e.target===r.id&&e.relationship==='SUPPORTED_BY')).map(e=><Button key={e.id} onClick={()=>open(e)}>Evidence: {e.title}</Button>)}</div></article>)}</div><p><a href="https://www.aicpa-cima.com/resources/download/2017-trust-services-criteria-with-revised-points-of-focus-2022" target="_blank" rel="noreferrer">SOC 2 Trust Services Criteria reference</a> · These local scenario labels are not official criterion identifiers.</p></section>
}
