CREATE TABLE IF NOT EXISTS tenants (id uuid PRIMARY KEY, name text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS users (id uuid PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), email text NOT NULL UNIQUE, name text NOT NULL, password_hash text NOT NULL, role text NOT NULL CHECK(role IN ('advisor','participant')), person_id uuid, company_id uuid, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS sessions (token_hash text PRIMARY KEY, user_id uuid NOT NULL REFERENCES users(id), csrf text NOT NULL, expires_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS invitations (token_hash text PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), company_id uuid NOT NULL, person_id uuid NOT NULL, email text NOT NULL, name text NOT NULL, expires_at timestamptz NOT NULL, used_at timestamptz, revoked_at timestamptz, request_id uuid NOT NULL);
CREATE TABLE IF NOT EXISTS companies (id uuid PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), name text NOT NULL, scope text NOT NULL, goal text NOT NULL, settings jsonb NOT NULL, sandbox boolean NOT NULL DEFAULT false, revision integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,id));
CREATE TABLE IF NOT EXISTS records (id uuid NOT NULL, tenant_id uuid NOT NULL, company_id uuid NOT NULL, kind text NOT NULL, title text NOT NULL, version integer NOT NULL CHECK(version>0), state text NOT NULL, data jsonb NOT NULL, hash text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(tenant_id,company_id,id), FOREIGN KEY(tenant_id,company_id) REFERENCES companies(tenant_id,id));
CREATE INDEX IF NOT EXISTS records_kind ON records(tenant_id,company_id,kind);
CREATE TABLE IF NOT EXISTS record_versions (tenant_id uuid NOT NULL, company_id uuid NOT NULL, record_id uuid NOT NULL, version integer NOT NULL, title text NOT NULL, data jsonb NOT NULL, hash text NOT NULL, actor_id uuid NOT NULL REFERENCES users(id), reason text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(tenant_id,company_id,record_id,version), FOREIGN KEY(tenant_id,company_id,record_id) REFERENCES records(tenant_id,company_id,id));
CREATE TABLE IF NOT EXISTS confirmations (id uuid PRIMARY KEY, tenant_id uuid NOT NULL, company_id uuid NOT NULL, record_id uuid NOT NULL, version integer NOT NULL, hash text NOT NULL, person_id uuid NOT NULL, user_id uuid NOT NULL REFERENCES users(id), request_id uuid NOT NULL, decision text NOT NULL CHECK(decision IN('correct','needs_change','not_mine','unsure')), note text NOT NULL DEFAULT '', accepted boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,company_id,record_id,version,person_id,request_id), FOREIGN KEY(tenant_id,company_id,record_id,version) REFERENCES record_versions(tenant_id,company_id,record_id,version));
CREATE TABLE IF NOT EXISTS audit_events (sequence bigserial PRIMARY KEY, id uuid NOT NULL UNIQUE, tenant_id uuid NOT NULL, company_id uuid NOT NULL, actor_id uuid NOT NULL, type text NOT NULL, record_id uuid, detail jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY(tenant_id,company_id) REFERENCES companies(tenant_id,id));
CREATE TABLE IF NOT EXISTS outbox (sequence bigserial PRIMARY KEY, id uuid NOT NULL UNIQUE, tenant_id uuid NOT NULL, company_id uuid NOT NULL, record_id uuid NOT NULL, version integer NOT NULL, type text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), processed_at timestamptz, FOREIGN KEY(tenant_id,company_id,record_id) REFERENCES records(tenant_id,company_id,id));
CREATE TABLE IF NOT EXISTS projection_nodes (tenant_id uuid NOT NULL, company_id uuid NOT NULL, record_id uuid NOT NULL, version integer NOT NULL, kind text NOT NULL, title text NOT NULL, state text NOT NULL, links jsonb NOT NULL, updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(tenant_id,company_id,record_id));
CREATE TABLE IF NOT EXISTS command_receipts (tenant_id uuid NOT NULL, actor_id uuid NOT NULL, key text NOT NULL, hash text NOT NULL, result jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(tenant_id,actor_id,key));
CREATE TABLE IF NOT EXISTS assets (id uuid NOT NULL, tenant_id uuid NOT NULL, company_id uuid NOT NULL, person_id uuid, request_id uuid, mime text NOT NULL, size integer NOT NULL, checksum text, state text NOT NULL DEFAULT 'uploading', created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(tenant_id,company_id,id), FOREIGN KEY(tenant_id,company_id) REFERENCES companies(tenant_id,id));
CREATE TABLE IF NOT EXISTS asset_chunks (tenant_id uuid NOT NULL, company_id uuid NOT NULL, asset_id uuid NOT NULL, chunk_index integer NOT NULL CHECK(chunk_index>=0), bytes bytea NOT NULL, checksum text NOT NULL, PRIMARY KEY(tenant_id,company_id,asset_id,chunk_index), FOREIGN KEY(tenant_id,company_id,asset_id) REFERENCES assets(tenant_id,company_id,id));
DO $$ DECLARE tbl text; BEGIN
  FOREACH tbl IN ARRAY ARRAY['companies','records','record_versions','confirmations','audit_events','outbox','projection_nodes','command_receipts','assets','asset_chunks'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',tbl);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY',tbl);
    IF NOT EXISTS(SELECT 1 FROM pg_policies WHERE tablename=tbl AND policyname='tenant_scope') THEN
      EXECUTE format('CREATE POLICY tenant_scope ON %I USING (tenant_id::text = current_setting(''app.tenant_id'',true)) WITH CHECK (tenant_id::text = current_setting(''app.tenant_id'',true))',tbl);
    END IF;
  END LOOP;
END $$;
