export const taskGranularityInstructions = `Separate ROLE, DUTY, TASK, and ACTION. A role carries duties; a duty is an ongoing responsibility; a task is a repeatable unit with a trigger, inputs, a checkable output and a recipient; actions are ordered steps within that task. Do not use a whole duty as one catch-all card. Split at a distinct output, handoff, system-changing operation, exception-resolution step, or human decision boundary. Keep small actions together when they produce the same result. A checklist comparison, record draft, exception resolution, verification handoff, status summary, and final approval routing can be separate tasks when the account supports them. Never turn every click into a task. Extract across all duties the person actually describes, not just the first one. Do not force six or ten cards or pad the result to a target count. Do not claim a person performs tasks they merely depend on. Name the upstream supplier of each input and the downstream recipient of each output when stated. Make each card usable by a replacement colleague: direct ordered steps, stated software, checks, exceptions and stop conditions. Keep unknown facts in gaps; do not invent system permissions, approvers, live integrations, or missing procedure details. Task confirmation records personal understanding only. AI suitability and authorization are separate downstream reviews; never infer permission to automate from employee confirmation.`;
export const granularWorkGuide = [
  "Name your regular duties. For each duty, list the repeatable tasks you do daily, weekly, or when an event occurs.",
  "For each task, what starts it? What data or documents arrive, who supplies them, and what must be complete?",
  "Explain the actions in order and the software used at each step. Separate checking, drafting, deciding, sharing, and updating a system when each produces its own result.",
  "What does a finished result look like? Who receives it, how do they receive it, and what work depends on it?",
  "Who do you depend on? What happens when information is missing, conflicting, or late? Which decisions need another person’s approval?",
  "If someone took over your role tomorrow, which other regular tasks, exceptions, or unwritten checks would they need to know?",
];
